In [7]:
import pandas as pd

pd.__version__

'2.0.3'

# Data Science Introduction

## Ingesting Data

To ingest data with `pandas`, commonly used is `csv`, ie, `pd.read_csv`

In [18]:
(df := pd.read_csv('../data/metrics.csv', index_col=0, parse_dates=[1]))

time period  calendarYear      revenue    netIncome  \
symbol                                                             
A      2022-07-31     Q3          2022   1718000000    329000000   
AA     2022-06-30     Q2          2022   3644000000    549000000   
AAL    2022-06-30     Q2          2022  13422000000    476000000   
AAP    2022-04-23     Q1          2022   3374210000    139791000   
AAPL   2022-06-25     Q3          2022  82959000000  19442000000   
...           ...    ...           ...          ...          ...   
YUM    2022-06-30     Q2          2022   1636000000    224000000   
ZBH    2022-06-30     Q2          2022   1781800000    153700000   
ZD     2022-06-30     Q2          2022    337356000    -46436000   
ZION   2022-06-30     Q2          2022    765000000    203000000   
ZTS    2022-06-30     Q2          2022   2052000000    529000000   

        operatingCashFlow  operatingMargin  freeCashFlow  dividendsPaid  \
symbol                                                                    
A            2.830000e+08            0.239  2.190000e+08  -6.300000e+07   
AA           5.360000e+08            0.180  4.290000e+08  -1.900000e+07   
AAL          1.739000e+09            0.076  1.047000e+09   0.000000e+00   
AAP         -5.494000e+07            0.060 -1.697940e+08  -1.547960e+08   
AAPL         2.289200e+10            0.278  2.079000e+10  -3.811000e+09   
...                   ...              ...           ...            ...   
YUM          2.690000e+08            0.339  2.140000e+08  -1.620000e+08   
ZBH          3.525000e+08            0.158  3.116000e+08  -5.030000e+07   
ZD           7.597300e+07            0.136  5.259900e+07   0.000000e+00   
ZION         5.160000e+08            0.000  5.160000e+08  -6.400000e+07   
ZTS          3.360000e+08            0.354  1.900000e+08  -1.530000e+08   

        dividendYield  peRatio  priceEarningsToGrowthRatio  pbRatio  \
symbol                                                                
A               0.002   32.538                     -15.293    6.962   
AA              0.002    3.788                       0.205    1.468   
AAL             0.008    4.331                       0.034   -0.979   
AAP             0.011   24.110                      -0.468    4.633   
AAPL            0.002   29.442                      -1.365   39.404   
...               ...      ...                         ...      ...   
YUM             0.005   36.232                      -0.833   -3.789   
ZBH             0.002   35.817                       0.038    1.817   
ZD              0.000  -18.850                       0.065    1.951   
ZION            0.008    9.443                      -0.148    1.361   
ZTS             0.002   38.180                      -3.700   17.639   

        priceToSalesRatio  enterpriseValueOverEBITDA  EBITDAOverRevenue  \
symbol                                                                    
A                  22.191                     85.736              0.242   
AA                  2.283                      8.631              0.267   
AAL                 0.614                     49.216              0.080   
AAP                 3.995                     58.344              0.083   
AAPL               27.600                     89.576              0.321   
...                   ...                        ...                ...   
YUM                19.843                     76.603              0.350   
ZBH                12.359                     59.031              0.264   
ZD                 10.379                     35.893              0.090   
ZION               10.023                     27.448              0.393   
ZTS                39.371                     99.268              0.409   

        debtToEquity  
symbol                
A              0.533  
AA             0.304  
AAL           -4.901  
AAP            1.209  
AAPL           1.630  
...              ...  
YUM           -1.347  
ZBH            0.437  
ZD             0.600  

In [29]:
df['abc'] = df.revenue - (df.freeCashFlow + df.operatingCashFlow)

In [30]:
df.columns

Index(['time', 'period', 'calendarYear', 'revenue', 'netIncome',
       'operatingCashFlow', 'operatingMargin', 'freeCashFlow', 'dividendsPaid',
       'dividendYield', 'peRatio', 'priceEarningsToGrowthRatio', 'pbRatio',
       'priceToSalesRatio', 'enterpriseValueOverEBITDA', 'EBITDAOverRevenue',
       'debtToEquity', 'abc'],
      dtype='object')

In [31]:
df.head()

time period  calendarYear      revenue    netIncome  \
symbol                                                             
A      2022-07-31     Q3          2022   1718000000    329000000   
AA     2022-06-30     Q2          2022   3644000000    549000000   
AAL    2022-06-30     Q2          2022  13422000000    476000000   
AAP    2022-04-23     Q1          2022   3374210000    139791000   
AAPL   2022-06-25     Q3          2022  82959000000  19442000000   

        operatingCashFlow  operatingMargin  freeCashFlow  dividendsPaid  \
symbol                                                                    
A            2.830000e+08            0.239  2.190000e+08  -6.300000e+07   
AA           5.360000e+08            0.180  4.290000e+08  -1.900000e+07   
AAL          1.739000e+09            0.076  1.047000e+09   0.000000e+00   
AAP         -5.494000e+07            0.060 -1.697940e+08  -1.547960e+08   
AAPL         2.289200e+10            0.278  2.079000e+10  -3.811000e+09   

        dividendYield  peRatio  priceEarningsToGrowthRatio  pbRatio  \
symbol                                                                
A               0.002   32.538                     -15.293    6.962   
AA              0.002    3.788                       0.205    1.468   
AAL             0.008    4.331                       0.034   -0.979   
AAP             0.011   24.110                      -0.468    4.633   
AAPL            0.002   29.442                      -1.365   39.404   

        priceToSalesRatio  enterpriseValueOverEBITDA  EBITDAOverRevenue  \
symbol                                                                    
A                  22.191                     85.736              0.242   
AA                  2.283                      8.631              0.267   
AAL                 0.614                     49.216              0.080   
AAP                 3.995                     58.344              0.083   
AAPL               27.600                     89.576              0.321   

        debtToEquity           abc  
symbol                              
A              0.533  1.216000e+09  
AA             0.304  2.679000e+09  
AAL           -4.901  1.063600e+10  
AAP            1.209  3.598944e+09  
AAPL           1.630  3.927700e+10

## Numpy basics (Algebra)

In [32]:
import numpy as np
np.__version__

'1.25.1'

In [64]:
x = np.random.rand(2, 3)
y = np.random.rand(3, 5)

In [65]:
x

array([[0.94598122, 0.73735721, 0.74657079],
       [0.95047969, 0.91965788, 0.43971151]])

In [66]:
y

array([[0.10514114, 0.539692  , 0.51652459, 0.07670309, 0.48035836],
       [0.98970707, 0.74920897, 0.53381426, 0.14883028, 0.01137307],
       [0.37860598, 0.30911997, 0.55993852, 0.36404695, 0.45789874]])

In [67]:
(a := x @ y)

array([[1.11188535, 1.29375307, 1.3002681 , 0.45408758, 0.80464982],
       [1.17660383, 1.33790583, 1.22808404, 0.3698533 , 0.66837354]])

In [68]:
x.T

array([[0.94598122, 0.95047969],
       [0.73735721, 0.91965788],
       [0.74657079, 0.43971151]])

In [69]:
y.T

array([[0.10514114, 0.98970707, 0.37860598],
       [0.539692  , 0.74920897, 0.30911997],
       [0.51652459, 0.53381426, 0.55993852],
       [0.07670309, 0.14883028, 0.36404695],
       [0.48035836, 0.01137307, 0.45789874]])

In [71]:
b = y.T @ x.T

In [72]:
b.shape

(5, 2)

In [73]:
a == b.T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [74]:
a, b.T

(array([[1.11188535, 1.29375307, 1.3002681 , 0.45408758, 0.80464982],
        [1.17660383, 1.33790583, 1.22808404, 0.3698533 , 0.66837354]]),
 array([[1.11188535, 1.29375307, 1.3002681 , 0.45408758, 0.80464982],
        [1.17660383, 1.33790583, 1.22808404, 0.3698533 , 0.66837354]]))

## Data Wrangling

In [75]:
df

time period  calendarYear      revenue    netIncome  \
symbol                                                             
A      2022-07-31     Q3          2022   1718000000    329000000   
AA     2022-06-30     Q2          2022   3644000000    549000000   
AAL    2022-06-30     Q2          2022  13422000000    476000000   
AAP    2022-04-23     Q1          2022   3374210000    139791000   
AAPL   2022-06-25     Q3          2022  82959000000  19442000000   
...           ...    ...           ...          ...          ...   
YUM    2022-06-30     Q2          2022   1636000000    224000000   
ZBH    2022-06-30     Q2          2022   1781800000    153700000   
ZD     2022-06-30     Q2          2022    337356000    -46436000   
ZION   2022-06-30     Q2          2022    765000000    203000000   
ZTS    2022-06-30     Q2          2022   2052000000    529000000   

        operatingCashFlow  operatingMargin  freeCashFlow  dividendsPaid  \
symbol                                                                    
A            2.830000e+08            0.239  2.190000e+08  -6.300000e+07   
AA           5.360000e+08            0.180  4.290000e+08  -1.900000e+07   
AAL          1.739000e+09            0.076  1.047000e+09   0.000000e+00   
AAP         -5.494000e+07            0.060 -1.697940e+08  -1.547960e+08   
AAPL         2.289200e+10            0.278  2.079000e+10  -3.811000e+09   
...                   ...              ...           ...            ...   
YUM          2.690000e+08            0.339  2.140000e+08  -1.620000e+08   
ZBH          3.525000e+08            0.158  3.116000e+08  -5.030000e+07   
ZD           7.597300e+07            0.136  5.259900e+07   0.000000e+00   
ZION         5.160000e+08            0.000  5.160000e+08  -6.400000e+07   
ZTS          3.360000e+08            0.354  1.900000e+08  -1.530000e+08   

        dividendYield  peRatio  priceEarningsToGrowthRatio  pbRatio  \
symbol                                                                
A               0.002   32.538                     -15.293    6.962   
AA              0.002    3.788                       0.205    1.468   
AAL             0.008    4.331                       0.034   -0.979   
AAP             0.011   24.110                      -0.468    4.633   
AAPL            0.002   29.442                      -1.365   39.404   
...               ...      ...                         ...      ...   
YUM             0.005   36.232                      -0.833   -3.789   
ZBH             0.002   35.817                       0.038    1.817   
ZD              0.000  -18.850                       0.065    1.951   
ZION            0.008    9.443                      -0.148    1.361   
ZTS             0.002   38.180                      -3.700   17.639   

        priceToSalesRatio  enterpriseValueOverEBITDA  EBITDAOverRevenue  \
symbol                                                                    
A                  22.191                     85.736              0.242   
AA                  2.283                      8.631              0.267   
AAL                 0.614                     49.216              0.080   
AAP                 3.995                     58.344              0.083   
AAPL               27.600                     89.576              0.321   
...                   ...                        ...                ...   
YUM                19.843                     76.603              0.350   
ZBH                12.359                     59.031              0.264   
ZD                 10.379                     35.893              0.090   
ZION               10.023                     27.448              0.393   
ZTS                39.371                     99.268              0.409   

        debtToEquity           abc  
symbol                              
A              0.533  1.216000e+09  
AA             0.304  2.679000e+09  
AAL           -4.901  1.063600e+10  
AAP            1.209  3.598944e+09  
AAPL           1.630  3.927700

In [80]:
df.describe().T

count                           mean  \
time                          641  2022-05-26 04:09:21.622465024   
calendarYear                641.0                    2021.985959   
revenue                     641.0             14230965399.263651   
netIncome                   641.0              2263745837.918877   
operatingCashFlow           641.0              3342779728.975039   
operatingMargin             641.0                      -2.637359   
freeCashFlow                641.0              2078183674.290172   
dividendsPaid               641.0              -599866672.868955   
dividendYield               641.0                      15.370404   
peRatio                     641.0                      23.337462   
priceEarningsToGrowthRatio  641.0                      29.497402   
pbRatio                     641.0                       7.373105   
priceToSalesRatio           641.0                     109.050805   
enterpriseValueOverEBITDA   641.0                      55.473195   
EBITDAOverRevenue           641.0                      -1.389226   
debtToEquity                641.0                       1.482477   
abc                         641.0               8810001995.99844   

                                            min                  25%  \
time                        2008-12-31 00:00:00  2022-06-30 00:00:00   
calendarYear                             2008.0               2022.0   
revenue                                     0.0          882000000.0   
netIncome                         -3418000000.0           70872000.0   
operatingCashFlow                 -7943000000.0           87670000.0   
operatingMargin                       -1386.897                0.066   
freeCashFlow                     -14135000000.0           19700000.0   
dividendsPaid                   -128873000000.0         -234000000.0   
dividendYield                               0.0                0.002   
peRatio                              -11377.661                7.046   
priceEarningsToGrowthRatio            -4677.586               -0.576   
pbRatio                                -269.506                1.592   
priceToSalesRatio                          0.02                4.545   
enterpriseValueOverEBITDA              -502.032               26.137   
EBITDAOverRevenue                       -1000.0                0.131   
debtToEquity                           -234.804                0.283   
abc                             -101321000000.0          411076000.0   

                                            50%                  75%  \
time                        2022-06-30 00:00:00  2022-06-30 00:00:00   
calendarYear                             2022.0               2022.0   
revenue                            2422000000.0         5602414000.0   
netIncome                           268800000.0          748985000.0   
operatingCashFlow                   333000000.0         1017000000.0   
operatingMargin                            0.15                0.238   
freeCashFlow                        206800000.0          756000000.0   
dividendsPaid                       -76565000.0           -5200000.0   
dividendYield                             0.005                0.009   
peRatio                                  16.702               28.844   
priceEarningsToGrowthRatio                0.048                0.777   
pbRatio                                   2.691                5.181   
priceToSalesRatio                         9.185               17.143   
enterpriseValueOverEBITDA                48.414               71.382   
EBITDAOverRevenue                         0.225                 0.38   
debtToEquity                              0.631                1.237   
abc                                1419400000.0         4085000000.0   

                                            max                  std  
time                        2022-07-31 00:00:00                  NaN  
calendarYear                             2023.0             0.68792

In [84]:
df.dropna()

time period  calendarYear      revenue    netIncome  \
symbol                                                             
A      2022-07-31     Q3          2022   1718000000    329000000   
AA     2022-06-30     Q2          2022   3644000000    549000000   
AAL    2022-06-30     Q2          2022  13422000000    476000000   
AAP    2022-04-23     Q1          2022   3374210000    139791000   
AAPL   2022-06-25     Q3          2022  82959000000  19442000000   
...           ...    ...           ...          ...          ...   
YUM    2022-06-30     Q2          2022   1636000000    224000000   
ZBH    2022-06-30     Q2          2022   1781800000    153700000   
ZD     2022-06-30     Q2          2022    337356000    -46436000   
ZION   2022-06-30     Q2          2022    765000000    203000000   
ZTS    2022-06-30     Q2          2022   2052000000    529000000   

        operatingCashFlow  operatingMargin  freeCashFlow  dividendsPaid  \
symbol                                                                    
A            2.830000e+08            0.239  2.190000e+08  -6.300000e+07   
AA           5.360000e+08            0.180  4.290000e+08  -1.900000e+07   
AAL          1.739000e+09            0.076  1.047000e+09   0.000000e+00   
AAP         -5.494000e+07            0.060 -1.697940e+08  -1.547960e+08   
AAPL         2.289200e+10            0.278  2.079000e+10  -3.811000e+09   
...                   ...              ...           ...            ...   
YUM          2.690000e+08            0.339  2.140000e+08  -1.620000e+08   
ZBH          3.525000e+08            0.158  3.116000e+08  -5.030000e+07   
ZD           7.597300e+07            0.136  5.259900e+07   0.000000e+00   
ZION         5.160000e+08            0.000  5.160000e+08  -6.400000e+07   
ZTS          3.360000e+08            0.354  1.900000e+08  -1.530000e+08   

        dividendYield  peRatio  priceEarningsToGrowthRatio  pbRatio  \
symbol                                                                
A               0.002   32.538                     -15.293    6.962   
AA              0.002    3.788                       0.205    1.468   
AAL             0.008    4.331                       0.034   -0.979   
AAP             0.011   24.110                      -0.468    4.633   
AAPL            0.002   29.442                      -1.365   39.404   
...               ...      ...                         ...      ...   
YUM             0.005   36.232                      -0.833   -3.789   
ZBH             0.002   35.817                       0.038    1.817   
ZD              0.000  -18.850                       0.065    1.951   
ZION            0.008    9.443                      -0.148    1.361   
ZTS             0.002   38.180                      -3.700   17.639   

        priceToSalesRatio  enterpriseValueOverEBITDA  EBITDAOverRevenue  \
symbol                                                                    
A                  22.191                     85.736              0.242   
AA                  2.283                      8.631              0.267   
AAL                 0.614                     49.216              0.080   
AAP                 3.995                     58.344              0.083   
AAPL               27.600                     89.576              0.321   
...                   ...                        ...                ...   
YUM                19.843                     76.603              0.350   
ZBH                12.359                     59.031              0.264   
ZD                 10.379                     35.893              0.090   
ZION               10.023                     27.448              0.393   
ZTS                39.371                     99.268              0.409   

        debtToEquity           abc  
symbol                              
A              0.533  1.216000e+09  
AA             0.304  2.679000e+09  
AAL           -4.901  1.063600e+10  
AAP            1.209  3.598944e+09  
AAPL           1.630  3.927700

In [87]:
df.drop_duplicates(subset=['period', 'calendarYear'])

time period  calendarYear      revenue   netIncome  \
symbol                                                            
A      2022-07-31     Q3          2022   1718000000   329000000   
AA     2022-06-30     Q2          2022   3644000000   549000000   
AAP    2022-04-23     Q1          2022   3374210000   139791000   
ADP    2022-06-30     Q4          2022   4000900000   625500000   
ADSK   2022-04-30     Q1          2023   1170000000   146000000   
ARCH   2022-06-30     Q2          2023   1133358000   407563000   
CCEP   2020-12-31     Q4          2020   2884500000   186000000   
CMP    2022-06-30     Q2          2021    214700000    -7900000   
CSL.AX 2020-09-30     Q1          2021   3315059012   765882267   
DE     2022-07-31     Q3          2023  13000000000  1884000000   
DGE.L  2018-12-31     Q2          2019            0           0   
PSON.L 2008-12-31     Q4          2008   1407174610   175386950   
XONE   2021-09-30     Q3          2021     19043000    -4907000   

        operatingCashFlow  operatingMargin  freeCashFlow  dividendsPaid  \
symbol                                                                    
A             283000000.0            0.239   219000000.0    -63000000.0   
AA            536000000.0            0.180   429000000.0    -19000000.0   
AAP           -54940000.0            0.060  -169794000.0   -154796000.0   
ADP           912900000.0            0.175   768600000.0   -434300000.0   
ADSK          434000000.0            0.183   422000000.0            0.0   
ARCH          268228000.0            0.373   236359000.0   -150716000.0   
CCEP                  0.0            0.105           0.0            0.0   
CMP             3000000.0           -0.016   -22400000.0     -5200000.0   
CSL.AX                0.0            0.293   408239837.0   -321688766.0   
DE            791000000.0            0.158    25000000.0   -322000000.0   
DGE.L         390647100.0           -2.062   308498160.0   -214667490.0   
PSON.L        178399788.0           -1.920   148524225.0    -63848345.0   
XONE           -4845000.0           -0.377    -5607000.0            0.0   

        dividendYield   peRatio  priceEarningsToGrowthRatio  pbRatio  \
symbol                                                                 
A               0.002    32.538                     -15.293    6.962   
AA              0.002     3.788                       0.205    1.468   
AAP             0.011    24.110                      -0.468    4.633   
ADP             0.005    34.914                      -1.077   27.084   
ADSK            0.007    70.332                       1.109   60.314   
ARCH            0.063     1.475                       0.039    2.022   
CCEP            0.014    25.855                       0.091    3.193   
CMP             0.004   -38.250                       6.885    4.017   
CSL.AX          0.002    42.431                     100.369   19.914   
DE              0.003    13.910                       0.105    6.175   
DGE.L           0.000  3468.289                    4559.917  731.725   
PSON.L          0.000  1462.606                    5381.310  109.003   
XONE            0.001   -26.321                      -2.193    3.283   

        priceToSalesRatio  enterpriseValueOverEBITDA  EBITDAOverRevenue  \
symbol                                                                    
A                  22.191                     85.736              0.242   
AA                  2.283                      8.631              0.267   
AAP                 3.995                     58.344              0.083   
ADP                21.834                     90.886              0.240   
ADSK               35.106                    169.082              0.215   
ARCH                2.121                      5.169              0.394   
CCEP                6.669                     60.881              0.142   
CMP                 5.630                     90.996              0.146   
CSL.AX             39.211                    135.8

## Indexing and Locating

In [93]:
(x := (np.random.rand(1000, 340) * 10).astype(int))

array([[9, 1, 2, ..., 2, 3, 6],
       [3, 5, 6, ..., 4, 5, 7],
       [6, 8, 6, ..., 7, 5, 3],
       ...,
       [0, 3, 4, ..., 2, 0, 6],
       [7, 1, 9, ..., 1, 6, 5],
       [8, 5, 0, ..., 1, 1, 6]])

In [96]:
(y := [int(random.random() * 10) for i in range(10)])

[7, 3, 9, 5, 2, 1, 1, 1, 4, 1]

In [111]:
x[:-2, 3:-1].shape  # 998 x 337

(998, 336)

In [125]:
df.loc[['A', 'AAPL', 'MSFT'], ['revenue', 'operatingCashFlow', 'netIncome']]

revenue  operatingCashFlow    netIncome
symbol                                             
A        1718000000       2.830000e+08    329000000
AAPL    82959000000       2.289200e+10  19442000000
MSFT    51865000000       2.462900e+10  16740000000

## Back to wrangling

In [145]:
(_filter := df.loc[:, 'revenue'] > df.revenue.quantile(0.5))

symbol
A       False
AA       True
AAL      True
AAP      True
AAPL     True
        ...  
YUM     False
ZBH     False
ZD      False
ZION    False
ZTS     False
Name: revenue, Length: 641, dtype: bool

In [146]:
df.loc[_filter]

time period  calendarYear       revenue    netIncome  \
symbol                                                               
AA      2022-06-30     Q2          2022    3644000000    549000000   
AAL     2022-06-30     Q2          2022   13422000000    476000000   
AAP     2022-04-23     Q1          2022    3374210000    139791000   
AAPL    2022-06-25     Q3          2022   82959000000  19442000000   
ABBN.SW 2022-06-30     Q2          2022    7251000000    379000000   
...            ...    ...           ...           ...          ...   
WRK     2022-06-30     Q3          2022    5519700000    377900000   
WY      2022-06-30     Q2          2022    2973000000    788000000   
X       2022-06-30     Q2          2022    6290000000    978000000   
XEL     2022-06-30     Q2          2022    3424000000    328000000   
XOM     2022-06-30     Q2          2022  111265000000  17850000000   

         operatingCashFlow  operatingMargin  freeCashFlow  dividendsPaid  \
symbol                                                                     
AA            5.360000e+08            0.180  4.290000e+08  -1.900000e+07   
AAL           1.739000e+09            0.076  1.047000e+09   0.000000e+00   
AAP          -5.494000e+07            0.060 -1.697940e+08  -1.547960e+08   
AAPL          2.289200e+10            0.278  2.079000e+10  -3.811000e+09   
ABBN.SW       3.820000e+08            0.081  2.310000e+08  -8.090000e+08   
...                    ...              ...           ...            ...   
WRK           8.374000e+08            0.098  6.220000e+08  -6.380000e+07   
WY            1.146000e+09            0.352  8.000000e+08  -1.340000e+08   
X             9.050000e+08            0.211  5.940000e+08   0.000000e+00   
XEL           8.480000e+08            0.137 -2.500000e+08  -2.570000e+08   
XOM           1.996300e+10            0.187  1.612600e+10  -3.727000e+09   

         dividendYield  peRatio  priceEarningsToGrowthRatio  pbRatio  \
symbol                                                                 
AA               0.002    3.788                       0.205    1.468   
AAL              0.008    4.331                       0.034   -0.979   
AAP              0.011   24.110                      -0.468    4.633   
AAPL             0.002   29.442                      -1.365   39.404   
ABBN.SW          0.017   32.060                      -0.904    3.961   
...                ...      ...                         ...      ...   
WRK              0.006    6.737                       0.008    0.889   
WY               0.005    7.823                       2.686    2.280   
X                0.001    1.178                       0.074    0.452   
XEL              0.007   29.447                      -2.061    2.419   
XOM              0.010    5.129                       0.022    2.065   

         priceToSalesRatio  enterpriseValueOverEBITDA  EBITDAOverRevenue  \
symbol                                                                     
AA                   2.283                      8.631              0.267   
AAL                  0.614                     49.216              0.080   
AAP                  3.995                     58.344              0.083   
AAPL                27.600                     89.576              0.321   
ABBN.SW              6.703                     67.051              0.113   
...                    ...                        ...                ...   
WRK                  1.845                     17.748              0.178   
WY                   8.294                     24.231              0.389   
X                    0.733                      3.781              0.238   
XEL                 11.284                     54.408              0.341   
XOM                  3.291                     13.663              0.259   

         debtToEquity           abc  
symbol                               
AA              0.304  2.679000e+09  
AAL            -4.901  1.063600e+10  
AAP             1.209  3.598944e+09 

In [159]:
filter_1 = df.revenue > df.revenue.quantile(0.5)
filter_2 = df.operatingCashFlow > df.operatingCashFlow.quantile(0.1)
filter_3 = df.debtToEquity < df.debtToEquity.quantile(0.1)
list(map(lambda x: x.shape, [df[filter_1], df[filter_2], df[filter_3]]))  # print chosen # of stocks for each filter

[(320, 18), (576, 18), (40, 18)]

In [164]:
df.loc[filter_1 & filter_2 & filter_3]

time period  calendarYear      revenue   netIncome  \
symbol                                                            
AAL    2022-06-30     Q2          2022  13422000000   476000000   
BA     2022-06-30     Q2          2022  16681000000   193000000   
CAH    2022-06-30     Q4          2022  47103000000   138000000   
HCA    2022-06-30     Q2          2022  14820000000  1155000000   
HD     2022-07-31     Q2          2023  43792000000  5173000000   
HPQ    2022-04-30     Q2          2022  16490000000  1000000000   
LOW    2022-04-29     Q1          2022  23659000000  2333000000   
LYV    2022-06-30     Q2          2022   4434174000   155240000   
MCD    2022-06-30     Q2          2022   5718400000  1188000000   
ORCL   2022-05-31     Q4          2022  11840000000  3189000000   
OTIS   2022-06-30     Q2          2022   3488000000   321000000   
PM     2022-06-30     Q2          2022   7832000000  2233000000   
SBUX   2022-07-03     Q3          2022   8150100000   912900000   
VMW    2022-04-29     Q1          2023   3088000000   242000000   

        operatingCashFlow  operatingMargin  freeCashFlow  dividendsPaid  \
symbol                                                                    
AAL          1.739000e+09            0.076  1.047000e+09   0.000000e+00   
BA           8.100000e+07            0.046 -1.820000e+08   0.000000e+00   
CAH          2.992000e+09            0.001  2.828000e+09  -1.340000e+08   
HCA          1.630000e+09            0.155  5.500000e+08  -1.600000e+08   
HD           3.789000e+09            0.165  3.085000e+09  -1.962000e+09   
HPQ          5.080000e+08            0.078  3.290000e+08  -2.620000e+08   
LOW          2.977000e+09            0.140  2.634000e+09  -5.370000e+08   
LYV          3.491380e+08            0.072  2.752560e+08   0.000000e+00   
MCD          6.181000e+08            0.299  1.802000e+08  -1.016900e+09   
ORCL         3.985000e+09            0.380  2.562000e+09  -8.540000e+08   
OTIS         3.530000e+08            0.140  3.260000e+08  -1.220000e+08   
PM           3.524000e+09            0.390  3.275000e+09  -1.945000e+09   
SBUX         1.264800e+09            0.159  8.413000e+08  -5.619000e+08   
VMW          1.005000e+09            0.132  8.990000e+08   0.000000e+00   

        dividendYield  peRatio  priceEarningsToGrowthRatio  pbRatio  \
symbol                                                                
AAL             0.008    4.331                       0.034   -0.979   
BA              0.014  105.143                       0.910   -5.452   
CAH             0.009   25.851                       0.235  -20.127   
HCA             0.003   10.641                      -1.723  -13.359   
HD              0.006   18.682                       0.686 -185.008   
HPQ             0.007    9.615                      -1.923  -20.264   
LOW             0.004   13.984                       0.145  -18.977   
LYV             0.000   29.879                       0.064  -45.235   
MCD             0.006   38.315                       4.905  -28.584   
ORCL            0.004   15.037                       0.396  -30.838   
OTIS            0.004   23.193                       5.644   -5.960   
PM              0.013   17.146                      -4.286  -16.933   
SBUX            0.006   24.978                       0.702  -10.524   
VMW             0.212    0.065                       0.000   -0.152   

        priceToSalesRatio  enterpriseValueOverEBITDA  EBITDAOverRevenue  \
symbol                                                                    
AAL                 0.614                     49.216              0.080   
BA                  4.866                     82.337              0.093   
CAH                 0.303                     29.038              0.004   
HCA                 3.317                     32.867              0.183   
HD                  8.126                     54.235              0.179   
HPQ                 2.332                     30.016              0.087   
LO

In [192]:
np.round((filter_1.astype(int) * 0.3 + 
filter_2.astype(int) *  0.25 + 
filter_3.astype(int) *  0.45) * 10, 0).astype(int).map(lambda x: [chr(65 + x) for x in range(10)][::-1][x - 1])

symbol
A       I
AA      E
AAL     A
AAP     H
AAPL    E
       ..
YUM     D
ZBH     I
ZD      I
ZION    I
ZTS     I
Length: 641, dtype: object

In [191]:
[chr(65 + x) for x in range(10)][::-1]

['J', 'I', 'H', 'G', 'F', 'E', 'D', 'C', 'B', 'A']